export const ICON_3D_ASSET_KEYS = [
  "calendar",
  "gauge",
  "map-pin",
  "search-vehicle",
  "compare-vehicles",
  "handshake-deal",
  "car-insurance",
  "security-advice",
  "car-financing",
  "car-import",
  "loan-calculator",
  "shield-check",
  "stopwatch-fast",
  "money-value",
  "instant-bolt",
  "market-chart",
  "community-users",
  "wallet",
  "verified-badge",
  "document-check",
  "listing-inspect",
  "car-front",
  "car-keys",
  "cash-hand",
  "chat-warning",
  "document-lock",
  "phishing-mail",
  "fraud-siren",
  "bell-alert",
  "email-envelope",
  "checklist",
  "shield-alert",
  "no-results",
  "empty-listings",
  "success-check",
  "rating-star",
  "role-buyer",
  "role-private-seller",
  "role-dealer",
  "phone-contact",
  "camera-photos",
  "upload-cloud",
  "add-to-compare",
  "ai-assistant",
  "listings-stack",
  "clock-pending",
  "favorites-heart",
  "chat-bubbles",
  "alert-circle",
  "link-chain",
  "security-lock",
  "file-review",
  "clipboard-decision",
  "package-open",
] as const;

export type Icon3DAssetKey = (typeof ICON_3D_ASSET_KEYS)[number];

// Only generated assets are listed; missing keys render the CSS badge fallback.
export const ICON_3D_ASSET_PATHS: Partial<Record<Icon3DAssetKey, string>> = {
  "calendar": "/assets/icons-3d/calendar.webp",
  "gauge": "/assets/icons-3d/gauge.webp",
  "map-pin": "/assets/icons-3d/map-pin.webp",
  "search-vehicle": "/assets/icons-3d/search-vehicle.webp",
  "compare-vehicles": "/assets/icons-3d/compare-vehicles.webp",
  "handshake-deal": "/assets/icons-3d/handshake-deal.webp",
  "car-insurance": "/assets/icons-3d/car-insurance.webp",
  "security-advice": "/assets/icons-3d/security-advice.webp",
  "car-financing": "/assets/icons-3d/car-financing.webp",
  "car-import": "/assets/icons-3d/car-import.webp",
  "loan-calculator": "/assets/icons-3d/loan-calculator.webp",
  "shield-check": "/assets/icons-3d/shield-check.webp",
  "stopwatch-fast": "/assets/icons-3d/stopwatch-fast.webp",
  "money-value": "/assets/icons-3d/money-value.webp",
  "instant-bolt": "/assets/icons-3d/instant-bolt.webp",
  "market-chart": "/assets/icons-3d/market-chart.webp",
  "community-users": "/assets/icons-3d/community-users.webp",
  "wallet": "/assets/icons-3d/wallet.webp",
  "verified-badge": "/assets/icons-3d/verified-badge.webp",
  "document-check": "/assets/icons-3d/document-check.webp",
  "listing-inspect": "/assets/icons-3d/listing-inspect.webp",
  "car-front": "/assets/icons-3d/car-front.webp",
  "car-keys": "/assets/icons-3d/car-keys.webp",
  "cash-hand": "/assets/icons-3d/cash-hand.webp",
  "chat-warning": "/assets/icons-3d/chat-warning.webp",
  "document-lock": "/assets/icons-3d/document-lock.webp",
  "phishing-mail": "/assets/icons-3d/phishing-mail.webp",
  "fraud-siren": "/assets/icons-3d/fraud-siren.webp",
  "bell-alert": "/assets/icons-3d/bell-alert.webp",
  "email-envelope": "/assets/icons-3d/email-envelope.webp",
  "checklist": "/assets/icons-3d/checklist.webp",
  "shield-alert": "/assets/icons-3d/shield-alert.webp",
  "no-results": "/assets/icons-3d/no-results.webp",
  "empty-listings": "/assets/icons-3d/empty-listings.webp",
  "success-check": "/assets/icons-3d/success-check.webp",
  "rating-star": "/assets/icons-3d/rating-star.webp",
  "role-buyer": "/assets/icons-3d/role-buyer.webp",
  "role-private-seller": "/assets/icons-3d/role-private-seller.webp",
  "role-dealer": "/assets/icons-3d/role-dealer.webp",
  "phone-contact": "/assets/icons-3d/phone-contact.webp",
  "camera-photos": "/assets/icons-3d/camera-photos.webp",
  "upload-cloud": "/assets/icons-3d/upload-cloud.webp",
  "add-to-compare": "/assets/icons-3d/add-to-compare.webp",
  "ai-assistant": "/assets/icons-3d/ai-assistant.webp",
  "listings-stack": "/assets/icons-3d/listings-stack.webp",
  "clock-pending": "/assets/icons-3d/clock-pending.webp",
  "favorites-heart": "/assets/icons-3d/favorites-heart.webp",
  "chat-bubbles": "/assets/icons-3d/chat-bubbles.webp",
  "alert-circle": "/assets/icons-3d/alert-circle.webp",
  "link-chain": "/assets/icons-3d/link-chain.webp",
  "security-lock": "/assets/icons-3d/security-lock.webp",
  "file-review": "/assets/icons-3d/file-review.webp",
  "clipboard-decision": "/assets/icons-3d/clipboard-decision.webp",
  "package-open": "/assets/icons-3d/package-open.webp",
};
