import type { ListingCategory } from "@/lib/constants/marketplace";

export type NonCarEquipmentTypeOption = {
  value: string;
  label: string;
  aliases?: readonly string[];
};

export type NonCarReferenceConfig = {
  makes: string[];
  modelInputMode: "manual";
  makeHelperText: string;
  modelHelperText: string;
};

export const PLANT_CONSTRUCTION_EQUIPMENT_TYPES = [
  { value: "excavator", label: "Excavator", aliases: ["excavators"] },
  { value: "bulldozer", label: "Bulldozer", aliases: ["bulldozers", "dozer", "dozers"] },
  { value: "loader", label: "Loader", aliases: ["loaders", "wheel loader", "wheel loaders"] },
  { value: "backhoe_loader", label: "Backhoe Loader", aliases: ["backhoe", "backhoes"] },
  { value: "crane", label: "Crane", aliases: ["cranes"] },
  { value: "forklift", label: "Forklift", aliases: ["forklifts", "lift truck"] },
  { value: "telehandler", label: "Telehandler", aliases: ["telehandlers"] },
  { value: "grader", label: "Grader", aliases: ["graders", "motor grader"] },
  { value: "roller_compactor", label: "Roller / Compactor", aliases: ["roller", "rollers", "compactor", "compactors"] },
  { value: "generator", label: "Generator", aliases: ["generators", "genset", "gensets"] },
  { value: "dumper", label: "Dumper", aliases: ["dumpers", "site dumper"] },
  { value: "compressor", label: "Compressor", aliases: ["compressors", "air compressor"] },
  { value: "concrete_mixer", label: "Concrete Mixer", aliases: ["concrete", "mixer", "mixers"] },
  { value: "aerial_platform", label: "Aerial Platform", aliases: ["aerial platforms", "boom lift", "scissor lift"] },
] as const satisfies readonly NonCarEquipmentTypeOption[];

export const FARM_AGRICULTURAL_EQUIPMENT_TYPES = [
  { value: "tractor", label: "Tractor", aliases: ["tractors"] },
  { value: "plough", label: "Plough", aliases: ["plow", "ploughs", "plows"] },
  { value: "harvester", label: "Harvester", aliases: ["harvesters", "combine", "combine harvester"] },
  { value: "baler", label: "Baler", aliases: ["balers"] },
  { value: "cultivator", label: "Cultivator", aliases: ["cultivators"] },
  { value: "planter", label: "Planter", aliases: ["planters", "seed drill", "seed drills"] },
  { value: "sprayer", label: "Sprayer", aliases: ["sprayers"] },
  { value: "trailer", label: "Trailer", aliases: ["trailers", "farm trailer"] },
  { value: "mower", label: "Mower", aliases: ["mowers"] },
  { value: "irrigation_equipment", label: "Irrigation Equipment", aliases: ["irrigation"] },
  { value: "feed_mixer", label: "Feed Mixer", aliases: ["feed mixers", "mixer wagon"] },
] as const satisfies readonly NonCarEquipmentTypeOption[];

export const NON_CAR_EQUIPMENT_TYPES_BY_CATEGORY: Partial<
  Record<ListingCategory, readonly NonCarEquipmentTypeOption[]>
> = {
  plant_construction: PLANT_CONSTRUCTION_EQUIPMENT_TYPES,
  farm_agricultural: FARM_AGRICULTURAL_EQUIPMENT_TYPES,
};

export const NON_CAR_REFERENCE_DATA: Partial<
  Record<ListingCategory, NonCarReferenceConfig>
> = {
  motorbike: {
    makes: [
      "AJS",
      "Aprilia",
      "BRP",
      "BSW",
      "Bajaj",
      "Benda",
      "Benelli",
      "Bertimati",
      "Beta",
      "Bimota",
      "BLAZE",
      "BMW Motorrad",
      "Boss Hoss",
      "Bridgestone",
      "Britt",
      "Brixton",
      "Buell",
      "Buggy",
      "CF Light",
      "CFMOTO",
      "COSWHEEL",
      "Cleveland",
      "DAELIM",
      "Daihatsu",
      "Ducati",
      "Electric Scooter",
      "Everest Exing",
      "Ex",
      "FB Mondial",
      "FUTURE",
      "Fantic",
      "Fellow",
      "Fuji Heavy Industries",
      "GLAFIT",
      "GPX",
      "Gas Gas",
      "Gilera",
      "Gotcia",
      "HYOSUNG",
      "Haojue",
      "Harley-Davidson",
      "Hero MotoCorp",
      "Honda",
      "Husqvarna",
      "Idea",
      "Italjet",
      "Italmoto",
      "KTM",
      "Kawasaki",
      "Kibo",
      "Kimiko",
      "Kobe",
      "Kove Mot",
      "Lambretta",
      "Leonart",
      "Lifan",
      "Loncin (VOGE)",
      "MEGELLI",
      "MV Agusta",
      "MZ",
      "Malaguti",
      "Mangosteen",
      "Marnie",
      "Mat",
      "Maverick",
      "Meguro",
      "Mobaeru",
      "Moriwaki",
      "Moto Guzzi",
      "Moto Morini",
      "Munch",
      "New Mitsubishi Heavy Industries",
      "Nicotto",
      "Norton",
      "PGO",
      "PHOENIX",
      "PXID",
      "Pajamas",
      "Panasonic",
      "Peugeot",
      "Piaggio",
      "Proto",
      "Pure",
      "QJMotor",
      "RICH BIT",
      "Rikuo",
      "Roam",
      "Rodeo",
      "Royal Alloy",
      "Royal Enfield",
      "SYM",
      "SNAKE MOTORS",
      "Saron",
      "Scorpa",
      "Senior Mobility Scooter",
      "Sherco",
      "Skomadi",
      "SkyTeam",
      "Snowbike",
      "Snowblower",
      "Snowmobile",
      "Solex",
      "Spiro",
      "Stallion",
      "Sun Emperor",
      "Suzuki",
      "Swallow",
      "SWM",
      "TVS",
      "TGB",
      "TM RACING",
      "TRRS",
      "Thunder Motorcycles",
      "Tohatsu",
      "Tomos",
      "Trike",
      "Triumph",
      "UM Motorcycles",
      "Ural",
      "Vectrix",
      "Vendor",
      "Vespa",
      "Victory",
      "Vincent",
      "VOGE",
      "YADEA",
      "Yamaguchi",
      "Yamaha",
      "Yoshimura",
      "Zongshen",
      "Zontes",
    ],
    modelInputMode: "manual",
    makeHelperText:
      "Suggested motorcycle brands are loaded from the operations catalog. If the brand is missing, type it manually.",
    modelHelperText:
      "Motorbike models remain manual for now. Enter the exact model as shown on the bike or logbook.",
  },
  truck: {
    makes: [
      "Bedford",
      "DAF",
      "Dongfeng",
      "FAW",
      "Foton",
      "Fuso",
      "Hino",
      "Howo",
      "Isuzu",
      "Iveco",
      "MAN",
      "Mercedes Benz",
      "Mitsubishi Fuso",
      "Nissan Diesel",
      "Renault",
      "Scania",
      "Shacman",
      "UD Trucks",
      "Volvo",
      "Yutong",
    ],
    modelInputMode: "manual",
    makeHelperText:
      "Suggested truck makes are loaded from the operations catalog. If the make is missing, type it manually.",
    modelHelperText:
      "Truck models remain manual for now. Enter the model exactly as used by the seller or registration record.",
  },
  plant_construction: {
    makes: [
      "ACM",
      "AG",
      "ARJES",
      "AW",
      "Aisle-Master",
      "Ammann",
      "Atlas",
      "Atlas Copco",
      "Attachment",
      "Augertorque",
      "Ausa",
      "Avant",
      "Aveling Barford",
      "Bateson",
      "BAV",
      "BCS",
      "BT",
      "Belle",
      "Benford",
      "BLACK ANDWHITE",
      "Bobcat",
      "Bomag Boss",
      "Brian James",
      "Buffalo",
      "Case",
      "Caterpillar",
      "Cherry",
      "Chieftain",
      "Claas",
      "Clark",
      "Clarke",
      "Combilift",
      "Conehead Chipper",
      "Conquip",
      "Containex",
      "Cookson And Zinn Cormidi",
      "Crytec Power Cushman",
      "Daewoo",
      "Dawson Keith Debon",
      "Dennison",
      "Develon",
      "Dieci",
      "Doosan",
      "Doppstadt",
      "Dynapac",
      "Easy Lift",
      "Ems Ltd",
      "Enduramaxx",
      "Fc Walker",
      "Fiat-hitachi",
      "Finlay",
      "Fiori",
      "Forst",
      "Fowler",
      "Garic",
      "Genie",
      "Giant Cycles",
      "Gileskips",
      "Goodwill",
      "Goodwin Barsby",
      "Gp",
      "Grasshopper",
      "Grove",
      "Hako",
      "Hamm",
      "Heli",
      "Hiab",
      "Hidromek",
      "Hitachi",
      "Hoist",
      "Husqvarna",
      "Hydrema",
      "Hydromix",
      "Hyster",
      "Hyundai",
      "Ifor Williams",
      "Impact",
      "Indeco",
      "Indespension",
      "Iveco",
      "J Mac",
      "JCB",
      "John Deere",
      "Johnston",
      "Jpm",
      "Jungheinrich",
      "Kaeser",
      "Kalmar",
      "Kato",
      "Kinshofer",
      "Kleemann",
      "Kmb",
      "Kobelco",
      "Komatsu",
      "Kommtek",
      "Kramer",
      "Kubota",
      "Lancer Boss",
      "Laski",
      "Ledburytokheim",
      "Leguan",
      "Liebherr",
      "Lifton",
      "Linde",
      "Liugong",
      "Loadmac",
      "Luigong",
      "Lynton",
      "Manitou",
      "Massey Ferguson",
      "Mecalac",
      "Meccalte",
      "Mercedes-Benz",
      "Merlo",
      "Messersi",
      "Metso",
      "Miscellaneous",
      "Mitsubishi",
      "Moffett",
      "Morooka",
      "Movex",
      "Moxy",
      "Nc",
      "Nc Engineering",
      "Neuson",
      "New Holland",
      "Niftylift",
      "Nissan",
      "Nugent",
      "Palfinger",
      "Pasquali",
      "Poggi",
      "Pramac",
      "Prodem",
      "Quicke",
      "R J Industrie",
      "Ransomes",
      "Raymo",
      "Rcm",
      "Red Rhino",
      "Redbrook",
      "Renault",
      "Rhino",
      "Rokbak",
      "Rotobec",
      "Sami",
      "Samuk",
      "Sany",
      "Secatol",
      "Security Cabin",
      "Sem",
      "Sennebogen",
      "Shantui",
      "Skyjack",
      "Slanetrac",
      "Smc",
      "Smv",
      "Snorkel",
      "Socage",
      "Staines",
      "Stephill",
      "Stiga",
      "Stihl",
      "Still",
      "Storage",
      "Strickland",
      "Strimech",
      "Sunward",
      "Swl",
      "Takeuchi",
      "Tennant",
      "Terex",
      "Thorworld",
      "Thurston Group",
      "Thwaites",
      "Tower Light",
      "Towmate Trailer",
      "Toyota",
      "Track Marshall",
      "Transcube",
      "Turbosol",
      "Venieri",
      "Vermeer",
      "Volvo",
      "Wacker Neuson",
      "Wbp Riddle Bucket",
      "Wbp Ripper Tooth",
      "Weidemann",
      "Western",
      "Wilcox",
      "Winget",
      "Woodford Trailers",
      "Xcmg",
      "Yale",
      "Yanmar",
    ],
    modelInputMode: "manual",
    makeHelperText:
      "Suggested plant and construction makes are loaded from the operations catalog. If the make is missing, type it manually.",
    modelHelperText:
      "Plant and construction models remain manual for now. Enter the exact model or machine code from the seller record.",
  },
  farm_agricultural: {
    makes: [
      "Belarus",
      "Case IH",
      "Claas",
      "Deutz-Fahr",
      "Escorts",
      "Fendt",
      "Ford",
      "John Deere",
      "Kubota",
      "Landini",
      "Mahindra",
      "Massey Ferguson",
      "McCormick",
      "New Holland",
      "SAME",
      "Sonalika",
      "TAFE",
      "Valtra",
      "Yanmar",
      "Zetor",
    ],
    modelInputMode: "manual",
    makeHelperText:
      "Suggested farm machinery makes are loaded from the operations catalog. If the make is missing, type it manually.",
    modelHelperText:
      "Farm machinery models remain manual for now. Enter the model, series, or implement code from the seller record.",
  },
};
