import type { ListingCategory } from "@/lib/constants/marketplace";

export type NonCarReferenceConfig = {
  makes: string[];
  modelInputMode: "manual";
  makeHelperText: string;
  modelHelperText: string;
};

export const NON_CAR_REFERENCE_DATA: Partial<
  Record<ListingCategory, NonCarReferenceConfig>
> = {
  motorbike: {
    makes: [
      "AJS",
      "Aprilia",
      "BRP",
      "BSW",
      "Bajaj",
      "Benda",
      "Benelli",
      "Bertimati",
      "Beta",
      "Bimota",
      "BLAZE",
      "BMW Motorrad",
      "Boss Hoss",
      "Bridgestone",
      "Britt",
      "Brixton",
      "Buell",
      "Buggy",
      "CF Light",
      "CFMOTO",
      "COSWHEEL",
      "Cleveland",
      "DAELIM",
      "Daihatsu",
      "Ducati",
      "Electric Scooter",
      "Everest Exing",
      "Ex",
      "FB Mondial",
      "FUTURE",
      "Fantic",
      "Fellow",
      "Fuji Heavy Industries",
      "GLAFIT",
      "GPX",
      "Gas Gas",
      "Gilera",
      "Gotcia",
      "HYOSUNG",
      "Haojue",
      "Harley-Davidson",
      "Hero MotoCorp",
      "Honda",
      "Husqvarna",
      "Idea",
      "Italjet",
      "Italmoto",
      "KTM",
      "Kawasaki",
      "Kibo",
      "Kimiko",
      "Kobe",
      "Kove Mot",
      "Lambretta",
      "Leonart",
      "Lifan",
      "Loncin (VOGE)",
      "MEGELLI",
      "MV Agusta",
      "MZ",
      "Malaguti",
      "Mangosteen",
      "Marnie",
      "Mat",
      "Maverick",
      "Meguro",
      "Mobaeru",
      "Moriwaki",
      "Moto Guzzi",
      "Moto Morini",
      "Munch",
      "New Mitsubishi Heavy Industries",
      "Nicotto",
      "Norton",
      "PGO",
      "PHOENIX",
      "PXID",
      "Pajamas",
      "Panasonic",
      "Peugeot",
      "Piaggio",
      "Proto",
      "Pure",
      "QJMotor",
      "RICH BIT",
      "Rikuo",
      "Roam",
      "Rodeo",
      "Royal Alloy",
      "Royal Enfield",
      "SYM",
      "SNAKE MOTORS",
      "Saron",
      "Scorpa",
      "Senior Mobility Scooter",
      "Sherco",
      "Skomadi",
      "SkyTeam",
      "Snowbike",
      "Snowblower",
      "Snowmobile",
      "Solex",
      "Spiro",
      "Stallion",
      "Sun Emperor",
      "Suzuki",
      "Swallow",
      "SWM",
      "TVS",
      "TGB",
      "TM RACING",
      "TRRS",
      "Thunder Motorcycles",
      "Tohatsu",
      "Tomos",
      "Trike",
      "Triumph",
      "UM Motorcycles",
      "Ural",
      "Vectrix",
      "Vendor",
      "Vespa",
      "Victory",
      "Vincent",
      "VOGE",
      "YADEA",
      "Yamaguchi",
      "Yamaha",
      "Yoshimura",
      "Zongshen",
      "Zontes",
    ],
    modelInputMode: "manual",
    makeHelperText:
      "Suggested motorcycle brands are loaded from the operations catalog. If the brand is missing, type it manually.",
    modelHelperText:
      "Motorbike models remain manual for now. Enter the exact model as shown on the bike or logbook.",
  },
  truck: {
    makes: [
      "Bedford",
      "DAF",
      "Dongfeng",
      "FAW",
      "Foton",
      "Fuso",
      "Hino",
      "Howo",
      "Isuzu",
      "Iveco",
      "MAN",
      "Mercedes Benz",
      "Mitsubishi Fuso",
      "Nissan Diesel",
      "Renault",
      "Scania",
      "Shacman",
      "UD Trucks",
      "Volvo",
      "Yutong",
    ],
    modelInputMode: "manual",
    makeHelperText:
      "Suggested truck makes are loaded from the operations catalog. If the make is missing, type it manually.",
    modelHelperText:
      "Truck models remain manual for now. Enter the model exactly as used by the seller or registration record.",
  },
  plant_construction: {
    makes: [
      "ACM",
      "AG",
      "ARJES",
      "AW",
      "Aisle-Master",
      "Ammann",
      "Atlas",
      "Atlas Copco",
      "Attachment",
      "Augertorque",
      "Ausa",
      "Avant",
      "Aveling Barford",
      "Bateson",
      "BAV",
      "BCS",
      "BT",
      "Belle",
      "Benford",
      "BLACK ANDWHITE",
      "Bobcat",
      "Bomag Boss",
      "Brian James",
      "Buffalo",
      "Case",
      "Caterpillar",
      "Cherry",
      "Chieftain",
      "Claas",
      "Clark",
      "Clarke",
      "Combilift",
      "Conehead Chipper",
      "Conquip",
      "Containex",
      "Cookson And Zinn Cormidi",
      "Crytec Power Cushman",
      "Daewoo",
      "Dawson Keith Debon",
      "Dennison",
      "Develon",
      "Dieci",
      "Doosan",
      "Doppstadt",
      "Dynapac",
      "Easy Lift",
      "Ems Ltd",
      "Enduramaxx",
      "Fc Walker",
      "Fiat-hitachi",
      "Finlay",
      "Fiori",
      "Forst",
      "Fowler",
      "Garic",
      "Genie",
      "Giant Cycles",
      "Gileskips",
      "Goodwill",
      "Goodwin Barsby",
      "Gp",
      "Grasshopper",
      "Grove",
      "Hako",
      "Hamm",
      "Heli",
      "Hiab",
      "Hidromek",
      "Hitachi",
      "Hoist",
      "Husqvarna",
      "Hydrema",
      "Hydromix",
      "Hyster",
      "Hyundai",
      "Ifor Williams",
      "Impact",
      "Indeco",
      "Indespension",
      "Iveco",
      "J Mac",
      "JCB",
      "John Deere",
      "Johnston",
      "Jpm",
      "Jungheinrich",
      "Kaeser",
      "Kalmar",
      "Kato",
      "Kinshofer",
      "Kleemann",
      "Kmb",
      "Kobelco",
      "Komatsu",
      "Kommtek",
      "Kramer",
      "Kubota",
      "Lancer Boss",
      "Laski",
      "Ledburytokheim",
      "Leguan",
      "Liebherr",
      "Lifton",
      "Linde",
      "Liugong",
      "Loadmac",
      "Luigong",
      "Lynton",
      "Manitou",
      "Massey Ferguson",
      "Mecalac",
      "Meccalte",
      "Mercedes-Benz",
      "Merlo",
      "Messersi",
      "Metso",
      "Miscellaneous",
      "Mitsubishi",
      "Moffett",
      "Morooka",
      "Movex",
      "Moxy",
      "Nc",
      "Nc Engineering",
      "Neuson",
      "New Holland",
      "Niftylift",
      "Nissan",
      "Nugent",
      "Palfinger",
      "Pasquali",
      "Poggi",
      "Pramac",
      "Prodem",
      "Quicke",
      "R J Industrie",
      "Ransomes",
      "Raymo",
      "Rcm",
      "Red Rhino",
      "Redbrook",
      "Renault",
      "Rhino",
      "Rokbak",
      "Rotobec",
      "Sami",
      "Samuk",
      "Sany",
      "Secatol",
      "Security Cabin",
      "Sem",
      "Sennebogen",
      "Shantui",
      "Skyjack",
      "Slanetrac",
      "Smc",
      "Smv",
      "Snorkel",
      "Socage",
      "Staines",
      "Stephill",
      "Stiga",
      "Stihl",
      "Still",
      "Storage",
      "Strickland",
      "Strimech",
      "Sunward",
      "Swl",
      "Takeuchi",
      "Tennant",
      "Terex",
      "Thorworld",
      "Thurston Group",
      "Thwaites",
      "Tower Light",
      "Towmate Trailer",
      "Toyota",
      "Track Marshall",
      "Transcube",
      "Turbosol",
      "Venieri",
      "Vermeer",
      "Volvo",
      "Wacker Neuson",
      "Wbp Riddle Bucket",
      "Wbp Ripper Tooth",
      "Weidemann",
      "Western",
      "Wilcox",
      "Winget",
      "Woodford Trailers",
      "Xcmg",
      "Yale",
      "Yanmar",
    ],
    modelInputMode: "manual",
    makeHelperText:
      "Suggested plant and construction makes are loaded from the operations catalog. If the make is missing, type it manually.",
    modelHelperText:
      "Plant and construction models remain manual for now. Enter the exact model or machine code from the seller record.",
  },
};
